//Listagem de todos tipos de ações do redux
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const FETCH_CLIENTS_REQUEST = "FETCH_CLIENTS_REQUEST";
export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";
export const FETCH_CLIENTS_FAILURE = "FETCH_CLIENTS_FAILURE";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";

export const FETCH_AMENITIES_REQUEST = "FETCH_AMENITIES_REQUEST";
export const FETCH_AMENITIES_SUCCESS = "FETCH_AMENITIES_SUCCESS";
export const FETCH_AMENITIES_FAILURE = "FETCH_AMENITIES_FAILURE";
export const CREATE_AMENITY_SUCCESS = "CREATE_AMENITY_SUCCESS";
export const UPDATE_AMENITY_SUCCESS = "UPDATE_AMENITY_SUCCESS";

export const FETCH_ACCOMMODATIONS_REQUEST = "FETCH_ACCOMMODATIONS_REQUEST";
export const FETCH_ACCOMMODATIONS_SUCCESS = "FETCH_ACCOMMODATIONS_SUCCESS";
export const FETCH_ACCOMMODATIONS_FAILURE = "FETCH_ACCOMMODATIONS_FAILURE";
export const CREATE_ACCOMMODATION_SUCCESS = "CREATE_ACCOMMODATION_SUCCESS";
export const UPDATE_ACCOMMODATION_SUCCESS = "UPDATE_ACCOMMODATION_SUCCESS";

export const FETCH_RESERVATIONS_REQUEST = 'FETCH_RESERVATIONS_REQUEST';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAILURE = 'FETCH_RESERVATIONS_FAILURE';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_SUCCESS = 'UPDATE_RESERVATION_SUCCESS';